# Held-out routing cases: NOT used to design the keyword regexes or the router examples,
# so this set is the honest accuracy measure.
# Append at least 10 of your own real commands here (the Plan says to few-shot with real
# utterances).
HELDOUT = [
    ("my python script keeps throwing a KeyError", "dev_agent"),
    ("why does npm install fail with EACCES", "dev_agent"),
    ("the build is red, what broke", "dev_agent"),
    ("explain this segmentation fault", "dev_agent"),
    ("pytest says assertion failed on line 40", "dev_agent"),
    ("check the price of a PS5 on Croma", "web_agent"),
    ("read the latest headlines from BBC", "web_agent"),
    ("look up reviews for the Pixel 9", "web_agent"),
    ("find a paneer tikka recipe on the internet", "web_agent"),
    ("boot up spotify", "os_agent"),
    ("shut down calculator", "os_agent"),
    ("make it louder", "os_agent"),
    ("mute the sound", "os_agent"),
    ("text Priya that dinner is ready", "os_agent"),
    ("bring up the task manager", "os_agent"),
    ("did I ever write down the wifi password", "rag_agent"),
    ("find my meeting minutes from Monday", "rag_agent"),
    ("look through what I saved about the visa", "rag_agent"),
    ("what does Krishna tell Arjun about duty", "rag_agent"),
    ("what is my gym locker number", "rag_agent"),
    ("where is the spare house key", "rag_agent"),
    ("when does my laptop warranty end", "rag_agent"),
    ("good morning", None), ("thanks a lot", None),
    ("who is the prime minister of Japan", None), ("is it a leap year", None),
    ("what is the speed of light", None), ("give me a fun fact", None),
    ("write me a haiku about rain", None),
    ("play something calm", "os_agent"),
    ("play believer on youtube", "os_agent"),
    ("open youtube music", "web_agent"),
    ("search for Samsung S26 on Flipkart please", "web_agent"),
    ("why is my terminal erroring after I ran npm start", "dev_agent"),
    ("close notepad", "os_agent"),
    ("what does my terminal say", "dev_agent"),
    ("shut down the computer", None),
]
