CASES = [
    ("open my browser", "web_agent"),
    ("search for Samsung S26 on Flipkart", "web_agent"),
    ("why is my terminal erroring", "dev_agent"),
    ("open vscode and check my terminal error", "dev_agent"),
    ("what does Gita 2.47 say", "rag_agent"),
    ("what does chapter 2 verse 47 say", "rag_agent"),
    ("what is in my notes about the blueprint", "rag_agent"),
    ("search my notes for the wifi password", "rag_agent"),
    ("open my editor", "os_agent"),
    ("open notepad", "os_agent"),
    ("play my favourite music", "os_agent"),
    ("pause the music", "os_agent"),
    ("close everything", "os_agent"),
    ("force close chrome", "os_agent"),
    ("message Arjun on WhatsApp that I'm running late", "os_agent"),
    ("volume up", "os_agent"),
    ("launch calculator", "os_agent"),
    ("open youtube", "web_agent"),
    ("go to flipkart.com", "web_agent"),
    ("there is a bug in my code", "dev_agent"),
    ("debug this", "dev_agent"),
    ("show me the stack trace", "dev_agent"),
    ("remember that my wifi is on the fridge", "rag_agent"),
    ("what did i do yesterday", "rag_agent"),
    ("hello there", None),
    ("what is the capital of France", None),
    ("tell me a joke", None),
    ("what time is it", None),
    ("OPEN MY BROWSER", "web_agent"),
    ("search google for pizza", "web_agent"),
]
